-- MySQL Script generated by MySQL Workbench
-- Mon Jan 23 23:49:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema only_beards
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema only_beards
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `only_beards` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`beard_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`beard_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `status` TINYINT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `updated_by` INT NULL,
  `created_by` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `only_beards` ;

-- -----------------------------------------------------
-- Table `only_beards`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `only_beards`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `id_beard_type` INT NULL DEFAULT NULL,
  `profile_picture` VARCHAR(50) NULL DEFAULT NULL,
  `bio_text` LONGTEXT NULL DEFAULT NULL,
  `profile_link` VARCHAR(45) NULL DEFAULT NULL,
  `beard_rutine` MEDIUMTEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `beard_type_idx` (`id_beard_type` ASC) VISIBLE,
  CONSTRAINT `beard_type`
    FOREIGN KEY (`id_beard_type`)
    REFERENCES `mydb`.`beard_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `only_beards`.`beard_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `only_beards`.`beard_score` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `score` INT NOT NULL,
  `id_scored_user` INT NOT NULL,
  `id_follower_score` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NOT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_scored_user_idx` (`id_scored_user` ASC) VISIBLE,
  INDEX `id_follower_score_idx` (`id_follower_score` ASC) VISIBLE,
  CONSTRAINT `id_follower_score`
    FOREIGN KEY (`id_follower_score`)
    REFERENCES `only_beards`.`users` (`id`),
  CONSTRAINT `id_scored_user`
    FOREIGN KEY (`id_scored_user`)
    REFERENCES `only_beards`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `only_beards`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `only_beards`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_author` INT NOT NULL,
  `text` LONGTEXT NULL DEFAULT NULL,
  `image` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NOT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_author_idx` (`id_author` ASC) VISIBLE,
  CONSTRAINT `id_author`
    FOREIGN KEY (`id_author`)
    REFERENCES `only_beards`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `only_beards`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `only_beards`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` LONGTEXT NOT NULL,
  `id_comment_author` INT NOT NULL,
  `id_post` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NOT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_comment_author_idx` (`id_comment_author` ASC) VISIBLE,
  INDEX `id_post_idx` (`id_post` ASC) VISIBLE,
  CONSTRAINT `id_comment_author`
    FOREIGN KEY (`id_comment_author`)
    REFERENCES `only_beards`.`users` (`id`),
  CONSTRAINT `id_post`
    FOREIGN KEY (`id_post`)
    REFERENCES `only_beards`.`posts` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `only_beards`.`follows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `only_beards`.`follows` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_follower` INT NOT NULL,
  `created_by` INT NOT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `id_follower_idx` (`id_follower` ASC) VISIBLE,
  CONSTRAINT `id_follower`
    FOREIGN KEY (`id_follower`)
    REFERENCES `only_beards`.`users` (`id`),
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `only_beards`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `only_beards`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `only_beards`.`likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_liked_post` INT NOT NULL,
  `id_user_liking` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `created_by` INT NOT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_liked_post_idx` (`id_liked_post` ASC) VISIBLE,
  INDEX `id_user_liking_idx` (`id_user_liking` ASC) VISIBLE,
  CONSTRAINT `id_liked_post`
    FOREIGN KEY (`id_liked_post`)
    REFERENCES `only_beards`.`posts` (`id`),
  CONSTRAINT `id_user_liking`
    FOREIGN KEY (`id_user_liking`)
    REFERENCES `only_beards`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
